language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules

script:
  - yarn install
  - yarn run cover
  - CI=false yarn run build

deploy:
  provider: heroku
  api_key:
    secure: $heroku_api_key
  skip_cleanup: true
  local_dir: dist
  on:
    all_branches: true